version: "3.9"

services:
  db:
    image: postgres:15
    container_name: stock-var-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stockdb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stock-var-backend
    restart: always
    depends_on:
      - db
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stockdb
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: >
      sh -c "chmod +x /app/entrypoint.sh && /app/entrypoint.sh"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stock-var-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000/api
    volumes:
      - ./frontend:/app
    command: >
      sh -c "npm install && npm run dev -- --host"

volumes:
  pg_data:
